<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
use App\Models\Quize;
use App\Models\Question;
use App\Models\Choice;

class QuizzesSeeder extends Seeder
{
    public function run(): void
    {
        $faker = Faker::create();

        for ($i = 1; $i <= 10; $i++) {
            $isAutoGenerated = $faker->boolean(30); // 30% احتمال أن يكون auto_generated

            $quiz = Quize::create([
                'from_video'        => $faker->numberBetween(1, 5),
                'to_video'          => $faker->numberBetween(6, 10),
                'title'             => $faker->sentence(3),
                'is_auto_generated' => $isAutoGenerated,
                'is_final'          => $faker->boolean(),
                'course_id'         => $faker->numberBetween(1, 10),
            ]);

            if (!$isAutoGenerated) {
                for ($j = 1; $j <= 10; $j++) {
                    $question = Question::create([
                        'text'     => $faker->sentence(8),
                        'quize_id' => $quiz->id,
                    ]);

                    $correctIndex = $faker->numberBetween(0, 3);

                    for ($k = 0; $k < 4; $k++) {
                        Choice::create([
                            'choice'      => $faker->sentence(4),
                            'question_id' => $question->id,
                            'is_correct'  => $k === $correctIndex,
                        ]);
                    }
                }
            }
        }
    }
}
